### ISSUE TITLE
  ;D تفکیک جنسیتی 

### ISSUE THREAD

**Issue by MohammadBarati** [sadjad-io/letters#1]
# #
<img width="564" alt="Screen Shot 1398-02-08 at 1 20 49 PM" src="https://user-images.githubusercontent.com/29622790/56861705-c1edd900-69b8-11e9-8a56-ff53bcc83353.png">

آقای نجمه ;D

>
 ************
صرفا برای فان این 
Issue  
************
>

 دمت گرم برای ریپوی باحال

**Comment by amirbagh75** [comment]
<span dir="rtl">

آره دیگه :)
ایده ای برای تشخیص جنسیت به جز db اسامی-جنسیت داری که بشه این مورد رو هم رفع کرد؟

</span>

**Comment by MohammadBarati** [comment]
@amirbagh75 
نه ایده ای به جز دیتابیس اسما به ذهنم نمیرسه ولی توی همون 
list.txt
میشه قبل اسمشون نوشت خانم یا آقا
راحت ترین کار همینه 
😄

**Comment by amirbagh75** [comment]
@MohammadBarati 
ایده خوبی دادی ولی خب داده های اساتید رو ما از سایت crawl کردیم و اولش اقا/خانم نداشت متاسفانه.

**Comment by MohammadBarati** [comment]
@amirbagh75 
نه دیگه پس xD
اگه اینطوری که راه دیگه ای فکر نکنم باشه جز همون 
db
